import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';

class Privacy extends StatelessWidget {
  const Privacy({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: SingleChildScrollView(
        padding: EdgeInsets.all(12),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisAlignment: MainAxisAlignment.start,
          children: [
            buildNavBar(context),
            headlineText(context, 'Privacy Policy'),
            bodyText(context, 'Last updated: May 05, 2021'),
            bodyText(
              context,
              """This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.""",
            ),
            bodyText(
              context,
              """We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.""",
            ),
            headlineText(context, 'Interpretation and Definitions'),
            headlineText(context, 'Interpretation'),
            bodyText(context,
                """The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural."""),
            headlineText(context, 'Definitions'),
            bodyText(context, """For the purposes of this Privacy Policy:
Account means a unique account created for You to access our Service or parts of our Service.
Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
Application means the software program provided by the Company downloaded by You on any electronic device, named SWINDER FOR INSTAGRAM
Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to EKSPAR SOFTWARE, ISTANBUL/BASAKSEHIR, 34490.
Country refers to: Turkey
Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.
Personal Data is any information that relates to an identified or identifiable individual.
Service refers to the Application.
Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.
Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
"""),
            headlineText(context, 'Collecting and Using Your Personal Data'),
            headlineText(context, 'Types of Data Collected'),
            headlineText(context, 'Personal Data'),
            bodyText(context,
                """While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:"""),
            bodyText(context, '-- Usage Data'),
            headlineText(context, 'Usage Data'),
            bodyText(context,
                """Usage Data is collected automatically when using the Service.
Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
"""),
            headlineText(
                context, 'Information from Third-Party Social Media Services'),
            bodyText(context,
                """The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:"""),
            bodyText(context, '-- Instagram'),
            bodyText(context,
                """If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We DO NOT collect your any private data such as Your name, Your email, Your activities or Your contact list associated with that account.
You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account.
"""),
            headlineText(
                context, 'Information Collected while Using the Application'),
            bodyText(context,
                """While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:"""),
            bodyText(context, '-- Information regarding your location'),
            bodyText(context,
                """We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.
You can enable or disable access to this information at any time, through Your Device settings.
"""),
            headlineText(context, 'Use of Your Personal Data'),
            bodyText(context,
                'The Company may use Personal Data for the following purposes:'),
            bodyText(context,
                """To provide and maintain our Service, including to monitor the usage of our Service.
To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.
For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.
To manage Your requests: To attend and manage Your requests to Us.
For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.
We may share Your personal information in the following situations:
"""),
            bodyText(context,
                """-- With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside."""),
            bodyText(context,
                """-- With Your consent: We may disclose Your personal information for any other purpose with Your consent."""),
            headlineText(context, 'Retention of Your Personal Data'),
            bodyText(context,
                """The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies."""),
            bodyText(context,
                """The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods."""),
            headlineText(context, 'Transfer of Your Personal Data'),
            bodyText(context,
                """Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
"""),
            headlineText(context, 'Disclosure of Your Personal Data'),
            headlineText(context, 'Business Transactions'),
            bodyText(context,
                """If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy."""),
            headlineText(context, 'Law enforcement'),
            bodyText(context,
                """Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency)."""),
            headlineText(context, 'Other legal requirements'),
            bodyText(context,
                """The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:"""),
            bodyText(context, """-- Comply with a legal obligation"""),
            bodyText(context,
                """-- Protect and defend the rights or property of the Company"""),
            bodyText(context,
                """-- Prevent or investigate possible wrongdoing in connection with the Service"""),
            bodyText(context,
                """-- Protect the personal safety of Users of the Service or the public"""),
            bodyText(context, """-- Protect against legal liability"""),
            headlineText(context, 'Security of Your Personal Data'),
            bodyText(context,
                """The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security."""),
            headlineText(context,
                'Detailed Information on the Processing of Your Personal Data'),
            bodyText(context,
                """The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies."""),
            headlineText(context, 'Advertising'),
            bodyText(context,
                """We may use Service Providers to show advertisements to You to help support and maintain Our Service."""),
            bodyText(context, """AdMob by Google"""),
            bodyText(context, """AdMob by Google is provided by Google Inc.
You can opt-out from the AdMob by Google service by following the instructions described by Google: https://support.google.com/ads/answer/2662922?hl=en
For more information on how Google uses the collected information, please visit the "How Google uses data when you use our partners' sites or app" page: https://policies.google.com/technologies/partner-sites or visit the Privacy Policy of Google: https://policies.google.com/privacy
"""),
            headlineText(context, "Children's Privacy"),
            bodyText(context,
                """Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers."""),
            bodyText(context,
                """If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information."""),
            headlineText(context, 'Links to Other Websites'),
            bodyText(context,
                """Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit."""),
            bodyText(context,
                """We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services."""),
            headlineText(context, 'Changes to this Privacy Policy'),
            bodyText(context,
                """We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
"""),
            headlineText(context, 'Contact Us'),
            bodyText(context,
                """If you have any questions about this Privacy Policy, You can contact us:"""),
            headlineText(context, 'By Email:'),
            bodyText(context, 'ebrar@ekspar.com.tr'),
            headlineText(context, 'By visiting this page on our website: :'),
            bodyText(context, 'https://ekspar.com.tr'),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                  'SWINDER © 2021',
                  style: TextStyle(color: Colors.grey),
                ),
              ],
            )
          ],
        ),
      ),
    );
  }

  //!BODY TEXT PADDING
  //  padding: EdgeInsets.symmetric(
  //       horizontal: MediaQuery.of(context).size.height * 0.4,
  //       vertical: MediaQuery.of(context).size.height * 0.008,
  //     ),

  //! HEADLINE TEXT PADDING
  // padding: EdgeInsets.symmetric(
  //         horizontal: MediaQuery.of(context).size.height * 0.4,
  //         vertical: MediaQuery.of(context).size.height * 0.01,
  //       ),

  Widget headlineText(BuildContext context, String text) => Text(
        text,
        style: Theme.of(context)
            .textTheme
            .headline6
            .copyWith(color: Colors.black, fontWeight: FontWeight.bold),
      );

  Widget bodyText(BuildContext context, String text) => Text(
        text,
        style:
            Theme.of(context).textTheme.bodyText1.copyWith(color: Colors.black),
      );

  Center buildNavBar(BuildContext context) => Center(
        child: Image.network(
          'http://swinderapp.com/assets/logo2.png',
          errorBuilder: (context, error, stackTrace) {
            return Image.asset(
              'assets/logo2.png',
              height: MediaQuery.of(context).size.height * 0.14,
            );
          },
          height: MediaQuery.of(context).size.height * 0.14,
        ),
      );
}
